name: frontend
description: "Oto Ekspertiz AI Mobil Uygulaması - AUTO-SCAN PRO"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0  # 🚀 GÜVENLİK İÇİN BU PAKETİ EKLEDİK
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  http: ^1.2.0
  desktop_window: ^0.4.2
  # Tasarımdaki modern yazı tipleri için ekledik
  google_fonts: ^6.2.1
  share_plus: ^12.0.2
  supabase_flutter: ^2.12.0
  device_info_plus: ^12.3.0
  purchases_flutter: ^9.16.1  # 🚀 RevenueCat ana paketi
  purchases_ui_flutter: ^9.15.1 # 🚀 Hazır ödeme arayüzleri için (isteğe bağlı)
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env